kpdecker/jsdiff

diff.js
Hi,
I am using AMD with an ember-cli app and it seems that JsDiff doesn't get loaded as a module unless you do a `define.amd` when you test for the `define` function.
I really don't know if this is correct pattern to do this but I've seen this behaviour in some other libraries and know it's loading correctly.
Cheers,
=> Fix AMD module loading

README.md, diff.js, index.html, test/diffTest.js
I extended the LineDiff.tokenize function to add the ability to ignore leading and trailing spaces when using TrimmedLineDiff, and added diffTrimmedLines to the public-facing functions. My changes should not affect any previous functionality.
=> Adding Diff Trimmed Lines

diff.js, test/diffTest.js
Need to be checked as I don't know what is the expected behavior for TrimmedLineDiff.
=> Fix for #51 Wrong result of JsDiff.diffLines

README.md, diff.js
When comparing strings that represent different versions, say 0.1.0/README and 0.1.1/README, it is nicer to include that metadata in the patch.
The proposed changes introduce createTwoFilesPatch, which allows it to take the old and new file names. createPatch calls the new function.
=> Two files patch

README.md, diff.js, test/createPatch.js, test/structuredPatch.js
This PR does two things: 1) gives control over the context size of patches, and 2) adds a method that allows retrieving a patch in the shape of an object with a list of hunks. E.g.:
```javascript
diff.structuredPatch(
'oldfile', 'newfile',
'line2\nline3\nline4\n', 'line2\nline3\nline5',
'header1', 'header2'
)
{
oldFileName: 'oldfile', newFileName: 'newfile',
oldHeader: 'header1', newHeader: 'header2',
hunks: [{
oldStart: 1, oldLines: 3, newStart: 1, newLines: 3,
lines: [' line2', ' line3', '-line4', '+line5', '\\ No newline at end of file'],
}]
}
```
If it looks acceptable, I'll patch documentation et cetera.
=> Allow access to structured object representation of patch data

src/patch/apply.js, test/patch/apply.js
This is related to issue https://github.com/kpdecker/jsdiff/issues/77
if previsousOperation doesn't exists, just continue.
also add two more test about this.
=> fix: error throwing when apply patch to empty string

src/patch/apply.js, test/patch/apply.js
If the destination lines length is 0, then actual editing should start one line later (since, per the spec, zero-length blocks are indexed at the line **before** any changes). This closes #116.
=> Add a fix for applying 0-length destination patches

README.md, src/patch/apply.js, test/patch/apply.js
=> Add callback argument to applyPatches `patched` option

README.md
Options of JsDiff.diffLines are not parsed as list in npmjs.com (CommonMark) due to indentation. This PR fixes such indentation.
=> Make README.md look nicer in npmjs.com

README.md, src/diff/array.js, src/diff/base.js, src/index.js, test/diff/array.js, test/index.js
adds support for comparing two arrays and finding the difference. This comes in very handy in my current project. 
If you feel this is beyond the boundaries of the primary focus of jsdiff which is text comparison, I could trim the pull request to just having the .join method move to the base class so we can create the diffArrays in our own project. Having the .join('') in several methods of base prevents this.
=> JsDiff.diffArrays to compare arrays

src/patch/apply.js, src/patch/parse.js, test/patch/parse.js
Split file using all possible line delimiter instead of hard-coded "/n" and join lines back using the original delimiters. 
let me know your feed back on this please.
=> Split file using all possible line delimiter instead of hard-coded "/n" and join lines back using the original delimiters

src/diff/json.js, test/diff/json.js
Fixes #155
Please, let me know if I need to change styling / rename `undefinedReplacement` to something more concise / anything else.
=> Add `undefinedReplacement` option to `diffJson`

src/index.js
Please try this (or something similar) and rebuild the NPM so 3-way-merge is available there.
=> Simple export of functionality

CONTRIBUTING.md
`grunt: command not found` because `grunt` isn’t installed globally on my computer?
The project installs it locally and therefore I can run it via `npm`
```json
"scripts": {
"test": "grunt"
},
```
=> Docs: Replace grunt with npm test in CONTRIBUTING.md

src/diff/array.js, test/diff/array.js
Fixes #173 
* Override `removeEmpty` method
* Add a test that failed first
=> Fix: diffArrays can compare falsey items

src/patch/apply.js, src/patch/parse.js
Currently, patches with empty lines such as:
```
-<link rel="resource" type="application/l10n" href="locale/locale.properties">
-<script src="pdf.viewer.js"></script>
+
```
are not fully applied because the parser stops at the empty line and the following operation is ignored.
=> Support patches with empty lines (#159)

src/diff/array.js, test/diff/array.js
In `buildValues` for `diffArray` the `value` property is an array, therefore the `slice` in the `join` method of the derived class is redundant, especially because the value is usually the result of `slice`
https://github.com/kpdecker/jsdiff/blob/master/src/diff/base.js#L181-L213
Because of the `slice` in the `tokenize` method of derived class, I added tests to prevent regression in apparent contract that no chunk value is ever an input argument. When I temporarily replaced `return value.slice();` with `return value;` two of the new assertions failed:
* does not return the input array
* does not return the second input array
However, all the existing tests passed, so if for equal or equivalent arrays, you see no problem with returning an input array as value of the one output chunk, then …
=> Omit redundant slice in join method of diffArrays

release-notes.md
The release notes appear twice, the commits list compares v3.5.0 to itself.
=> Remove duplicated release notes for v3.5.0

src/diff/word.js, test/diff/word.js
This produces more natural diffs in situations like `()` -> `(word)`
=> Make ()[]"' as word boundaries between each other

src/patch/create.js, test/patch/create.js
=> Fix: Missing "No newline at end of file" when comparing two texts that do not end in newlines

style.css
I use this tool regularly. (thanks for making it)
Once thing that usually bugs me is how long lines are handled. So here's a small fix.
Before:
After:
=> wrap the result column

package.json
A [search for `jsdiff` on npmjs.com](https://www.npmjs.com/search?q=jsdiff) does not include *jsdiff* in the results, though an apparent imposter is the number one hit. 
I added some additional keywords which I believe will help people find the diff tool they are looking for 😉 , but feel free to edit this pull request as you see fit.
=> Added keywords to improve npm discoverability.

package.json, rollup.config.js
Closes #292 
Used the "loose" variant so that this won't be accidentally breaking for users who are spelunking into the `dist` or `lib` directories for specific file(s). 
There's an issue with Node 13.0 through 13.6 that shipped early, now-deprecated versions of the `exports` map syntax. 
Any users on those versions _should have already_ abandoned them, since any odd major release (especially early versions of it) are always experimental.
The current `exports` map works in all 12.x and 14.x versions (and 13.7+). 
It's completely ignored by older versions of Node since they don't know what it is.
---
While completely unrelated, I also added the `unpkg` key so that developers can do this, if they want:
```html
<script src="https://unpkg.com/diff"></script>
```
=> Feat: Add `exports` map for Native ESM

src/diff/word.js, test/diff/word.js
=> Threat each newline as separate word in `diffWordsWithSpace`

src/patch/create.js, test/patch/create.js
This allows for using a structured patch and serializing it later on.
Currently, when I want to work with the hunks and have a string version of the patch later on, I need to perform the diff twice.
=> Separate patch creation from serialization.

style.css
Thanks for the great repo!
I am suggesting a minor change to improve readability of results, by adding a word wrap for the use case when the compared text doesn't have line space and it's all on one line, it make it easier to ready in results.
```css
#result {
white-space: pre-wrap;
}
```
=> added word wrap on results div

package.json, src/patch/create.js, src/patch/parse.js, test/patch/apply.js, test/patch/create.js
Based on the description here:
https://www.artima.com/weblogs/viewpost.jsp?thread=164293
which matches the behavior of the `diff`/`patch` tools.
For all of the tests created or modified, behavior was verified
to match that of `diff`/`patch`.
Fixes #296
=> Update to match quirks of unified diff format

README.md
GitHub pages now uses github.io domain.
Since https://kpdecker.github.io/jsdiff redirects to http://incaseofstairs.com/jsdiff/ we could also use this URL.
=> Fix online demo URL

README.md, test/patch/create.js
The documentation states that createPatch only supports `context`, when in actuality it passes the options on to the diffLines implementation. 
This PR updates the documentation to clarify this and also adds tests to verify this behavior. 
Since these methods are supposed to output a patch, it's arguable that the options doesn't make sense, but I'd argue that the `ignoreWhitespace` at least makes sense since outputting a patch is a pretty normalized way to display a diff and it makes sense to be able to use the existing options for it. 
`newLineIsToken` is a bit weirder when creating "patches". I added docs and tests for that in separate [commit](https://github.com/kpdecker/jsdiff/commit/12eb1729c64ebcd3b9f1d81c289c9502d465bae9) so that it can be reverted if it's something that is not …
=> Document and test options to createPatch

src/diff/base.js, src/patch/create.js, test/diff/line.js, test/patch/create.js
Fixes #364 by giving callers an option.
=> Allow early termination to limit execution time with degenerate cases

README.md, components/component.json, package.json, src/index.js
Nothing of consequence, here - just fixing some miscapitalised words in prose that I noticed while working on more important things.
=> Fix assorted trivial capitalisation typos

yarn.lock
Dependabot wants to upgrade lots of packages - e.g. https://github.com/kpdecker/jsdiff/pull/394
We probably don't care about _any_ of the vulnerabilities Dependabot is grumbling about, since they're all just dev dependencies. Nonetheless, it'd be nice to clear out the PRs, and I think this should do that.
Since the project is using Yarn 1, I don't think there's any properly supported way to upgrade transitive dependencies, so the approach I took was, for each Dependabot PR, to:
1. Delete any top-level entries for the package from `yarn.lock`
2. Run e.g. `yarn && yarn test && git commit -am "Upgrade elliptic"` to write the latest package.json-compatible version into `yarn.lock`, run the tests to check this doesn't break anything, and then commit
(I haven't bothered to check that this …
=> Upgrade packages that Dependabot has open PRs about

examples/node_example.js, karma.conf.js, rollup.config.js, tasks/version.js
We have a .eslintrc, but we don't seem to be respecting it; `yarn eslint .` gets grumpy about lots of things. This fixes the autofixable ones, and in the process:
* Closes https://github.com/kpdecker/jsdiff/pull/405
* Closes https://github.com/kpdecker/jsdiff/pull/406
* Closes https://github.com/kpdecker/jsdiff/pull/407
Something is broken with our eslint config; `yarn eslint .` and `yarn grunt eslint` give radically different results, perhaps suggesting they're using different rule sets? I'll make an issue about that.
=> yarn eslint . --fix

package.json
As @paultinker notes in https://github.com/kpdecker/jsdiff/issues/413, version 5.1.0 of jsdiff was released to npm last year, but the package.json in the repo still says we're on 5.0.0. Let's update the repo!
=> Update package.json version to 5.1.0

yarn.lock
My cleanup of https://github.com/kpdecker/jsdiff/pull/415 brought Dependabot out of hibernation and caused it to open a bunch more PRs bumping dependencies. I've bumped _those_ dependencies too, using the same strategy as last time. This should close all the Dependabot PRs. `yarn test` is passing.
=> Bump more dependencies to please Dependabot

README.md
I ran into this because `undefined` keys in the diff don't show up, so I needed to supply an undefined replacement
=> Document diffJson() options

package.json
Fixes #350
[A solution that postss used](https://github.com/postcss/postcss/commit/92155c73e105a36af5196a75bcc34ada377a711f) seems unnecessary, as I tested, use `"./*": "./*"` works on Node.js 12 too.
=> Fix `exports` field in `package.json`

src/patch/apply.js, test/patch/apply.js
Fixes #228
Since a structured patch does not define its line delimiters (#157), this change is needed to prevent an error when the returned value of `structuredPatch` is used in `applyPatch`. The current API does not change:
```js
const oldContent = 'ANYTHING';
const newContent = 'SOMETHING';
const patch = structuredPatch('test.txt', 'test.txt', oldContent, newContent);
expect(applyPatch(oldContent, patch)).to.equal(newContent);
```
=> Default value of line delimiters when a patch is applied (#228)

README.md, src/diff/line.js, test/diff/line.js, test/patch/create.js
Simple idea/suggestion.
Fixes #343, #275
See #343 for in-depth explanation.
=> Option to strip trailing CR

test/patch/apply.js
Over at #177, @dolftax reported a particular example of a patch that `applyPatch` handled incorrectly. However, this test seems to indicate that we no longer apply at least that particular patch incorrectly. Possibly the fix to https://github.com/kpdecker/jsdiff/issues/189 also fixed #177?
Resolves #177.
=> Add test showing patch from bug #177 is handled correctly now

src/diff/base.js
Until now, jsdiff's entire implementation has been kind of symmetrically flipped from the algorithm described in the Myers paper. In Myers' paper, each column in the edit graph corresponds to a character in the OLD text (and hence horizontal movements correspond to deletions), while each ROW corresponds to a character in the NEW text (and hence vertical movements correspond to insertions). See page 4:
> ... each horizontal edge to point (x,y) corresponds to the delete command ‘‘x D’’; and a sequence of
vertical edges from (x,y) to (x,z) corresponds to the insert command ...
The numbers of diagonals, meanwhile, are such that a larger diagonal number corresponds to having a higher *x* - i.e. having done more *deletions*:
> Number the diagonals in the grid of edit graph vertices so that …
=> Flip core algorithm so everything is no longer the mirror image of Myers's paper

CONTRIBUTING.md
Previously we did this in the title of the README but then used a different casing in CONTRIBUTING.md, and I was unsure which to use when adding further mentions of the library's name. This change brings consistency.
=> Consistently capitalize "jsdiff" in all-lowercase in docs

README.md, release-notes.md, src/index.js, src/patch/create.js, test/patch/create.js
Resolves https://github.com/kpdecker/jsdiff/issues/109
=> Expose `formatPatch` on `diff` object and document

README.md, release-notes.md, src/index.js, src/patch/reverse.js, test/patch/reverse.js
Resolves https://github.com/kpdecker/jsdiff/issues/105
(Code based on @ericbiewener's contribution in that issue.)
=> Add function to reverse a patch

README.md, release-notes.md, src/diff/base.js, test/diff/character.js, test/diff/line.js
Resolves https://github.com/kpdecker/jsdiff/issues/148
To Do:
- Tests:
=> Add a oneChangePerToken option

release-notes.md, src/diff/base.js, test/diff/array.js
Intuitively you would expect that values from the old text/array would get passed as the `left` argument and values from the new would get passed as the `right` argument, but this was not the case. This PR makes it so.
Resolves https://github.com/kpdecker/jsdiff/issues/286.
=> Fix order of arguments to .equals and comparator

package.json, yarn.lock
Resolves https://github.com/kpdecker/jsdiff/issues/337
As I understand it, the original maintainer of the `colors` package, Marak, previously sabotaged it for a laundry list of political/ideological reasons, involving Aaron Schwartz, the Ukraine war, and big corporations using his code. npm removed the malicious version against the old maintainer's will, but one still has to wonder if he might one day sabotage his packages again. Anything by him is kinda suspect, now.
Someone else called DABH took over maintainership after the sabotage. Let's point at the npm package _he_ controls, just to be sure that bumping our dev dependencies in future won't install malware.
The (tiny, trivial) example script that uses `colors` still seems to work after this:
=> Migrate to DABH's fork of colors

README.md
(Clicking the VIEW PDF button at https://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.4.6927 just takes me to an error page saying `{"message":"Token is required"}`.)
=> Replace broken link to Myers's paper in the README with a working one

README.md, release-notes.md, src/diff/base.js, test/diff/array.js
Resolves https://github.com/kpdecker/jsdiff/issues/398
To do:
=> Add `timeout` option

README.md, examples/node_example.js
Resolves https://github.com/kpdecker/jsdiff/issues/414
As noted there, we can't color *both* the background and text in green/red of different shades, like the HTML example does, because terminals only support a limited number of shades and "red" text on "bright red" background is almost completely illegible on some terminals. Therefore this PR swaps us from coloring ONLY the text to instead coloring ONLY the background. This should still clearly show what letters are added/deleted, but now also makes added/deleted spaces visible, which they weren't before.
Here's a screenshot showing the behaviour change:
=> Modify node_example.js to support showing added/deleted spaces

README.md, release-notes.md, src/patch/create.js, test/patch/create.js
Resolves https://github.com/kpdecker/jsdiff/issues/463
=> Support max edit length in patch creation functions

test/diff/line.js
As suggested at https://github.com/kpdecker/jsdiff/pull/486#issuecomment-1946386203, I've copied the tests @Mingun previously wrote for this feature (with minor tweaks).
Thanks for the help, @Mingun!
=> Add some more exhaustive tests of ignoreWhitespace based on @Mingun's work

README.md, release-notes.md, src/diff/base.js, test/diff/word.js
Previously, the `callback` option had to be a function that takes the result as its *second* argument; the first argument, meanwhile, was never used. (Some tests name the parameter `err`; however, there is absolutely no circumstance in which an error, or anything besides `undefined`, will be passed as the value of that argument.)
This PR fixes this (utterly breaking backwards compat in the process) by making the result be passed as the value of the FIRST argument.
Resolves https://github.com/kpdecker/jsdiff/issues/462
=> Fix the weird function signature of async callbacks

test/diff/line.js
When I added this test, I decided to modify the assertion it makes to be easier to understand and verify the correctness of at a glance, at the expense of making it a less robust test of the behaviour. @Mingun indicated his disagreement with this at https://github.com/kpdecker/jsdiff/pull/488#discussion_r1491619027 and I immediately agreed he had a point, so I've added the more rigorous assertion back in alongside the readable one.
Interestingly, just directly copying @Mingun's assertion failed; @Mingun's version ends with:
```
'<del>]</del><ins>  ]\n',
'}</ins>'
```
but with my version of the `ignoreWhitespace` code, the line with the `]` on it isn't treated as deleted and re-inserted at all, simply as equal/preserved. I guess this is a difference in how @Mingun's logic from …
=> Add further assertion to test, as suggested by Mingun

src/diff/json.js, test/diff/json.js
Addresses https://github.com/kpdecker/jsdiff/issues/492
I was recently trying to use `diff` to compare output from a library that makes use of `Object.create(null)`.  This seems valid (if not encouraged) in some situations, but `diff` was throwing as the `typeof` this is `'object'` and it is `!== null` but `obj.hasOwnProperty` does not exist.
Instead, use `Object.prototype.hasOwnProperty.call(obj, key)` similar to the way that `Object.prototyope.toString` is used elsewhere in this library.
=> Support `Object.create(null)` in JSON diffing

src/diff/word.js, test/diff/word.js
This eliminates all the logic about rejoining boundary splits. It was dumb; we were doing an initial split into tokens based on a Unicode-naive notion of "word characters", and then bandaging some words back together with a Unicode-aware regex, when we could instead just use the Unicode-aware regex to start with.
I actually wrote this intending it to just be a refactor that would make it easier to make further fixes to `diffWords`, but I think 
I inadvertently fixed two bugs along the way! Namely, those bugs are:
* https://github.com/kpdecker/jsdiff/issues/311
* that when tokenizing text containing Windows-style newlines, the carriage return and line feed characters would each get their own token instead of being grouped into a single newline token
The test failure below is what you get …
=> Simplify tokenization logic in diffWords

test/diff/word.js
(Just something I spotted we didn't test, and wanted to confirm I wasn't breaking over in https://github.com/kpdecker/jsdiff/pull/497)
=> Add test of how diffWordsWithSpace handles Windows-style newlines

package.json, yarn.lock
The latest tiny step in my attempts to upgrade the build pipeline used by this project. (I want it all up to date so that when I [introduce TypeScript](https://github.com/kpdecker/jsdiff/pull/496), I can rely on the latest docs for the tools being used. I am not very knowledgeable about JavaScript build tools and if I have to try to figure out how to make stuff work with versions of them that are years out of date then I'm going to end up tearing my hair out.)
Upgrading to version 8 breaks stuff, currently, which is why I'm only going up one major version at the moment. Output of `yarn test` with version 8 is as follows:
```
Running "mocha_istanbul:coverage" (mocha_istanbul) task
/home/mark/jsdiff/test/convert/dmp.js:1
import {convertChangesToDMP} from '../../lib/convert/dmp';
^^^^^^ …
```
=> Bump Mocha one major version

README.md, release-notes.md, src/patch/create.js, test/patch/create.js
=> Support `callback` in patch functions, not just diffFoo functions

README.md, release-notes.md, src/patch/create.js, test/patch/create.js
Fixes https://github.com/kpdecker/jsdiff/issues/531.
But also rips out the ability to pass `newlineIsToken` to `createPatch` et al, because my changes here broke the tests (that @oBusk had added in https://github.com/kpdecker/jsdiff/pull/345) for that feature and when I dug into it I realised - like I think @oBusk kinda implies in that PR description - that the whole feature is kinda broken, since it causes line ending changes to get falsely represented as deletions and insertions of entire blank lines in the patch.
(I suspect @Kiougar didn't consider the `newlineIsToken` option specifically back in 2016 when he wrote https://github.com/kpdecker/jsdiff/pull/153, and was probably thinking primarily about options like `ignoreWhitespace` which *do* make sense to pass to patch functions.)
=> Fix handling of EOF in createPatch

rollup.config.mjs
I haven't tested everything on Node 22 yet, but this should stop at least one way the build is broken in Node 22. Fixes https://github.com/kpdecker/jsdiff/issues/537.
=> Stop using old 'import assertions' syntax that was removed in Node 22

.npmignore
Should've been done as part of https://github.com/kpdecker/jsdiff/pull/505, but I missed it
=> Fix reference to no-longer-existent 'rollup.config.js' file

src/util/string.js
Resolves https://github.com/kpdecker/jsdiff/issues/545, I think.
=> Remove use of regex lookbehind to improve compat with old Safari versions

release-notes.md
Just another little thing I recently broke!
=> Fix links to commit lists in release-notes.md

release-notes.md, src/diff/word.js, test/diff/word.js
Fixes https://github.com/kpdecker/jsdiff/issues/553 (the original issue, not the orthogonal bug posted in a comment).
The bug was introduced in https://github.com/kpdecker/jsdiff/pull/494. Previously we were splitting into words on [`\b`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Word_boundary_assertion), which per the linked MDN docs considers the following things to be word characters:
> Letters (A–Z, a–z), numbers (0–9), and underscore (_).
Then I swapped to using the `extendedWordChars` regex (previously only used for stitching together some adjacent tokens into single tokens after the original splitting), but didn't ensure it actually contained all the things that `\b` considers to be word characters.
This should fix it!
=> Fix diffWords treating numbers and underscores as not being word characters

README.md, release-notes.md, src/diff/sentence.js, test/diff/sentence.js
The performance bug here was essentially the same as what I describe at https://markamery.com/blog/quadratic-time-regexes/; essentially, doing a regex search using a regex that starts with a pattern repeated with `+` or `*` is by default a quadratic time operation, unless you put a lookbehind before it, which we weren't doing.
While adding tests to check I wasn't breaking anything with this fix, I realised some existing behaviour was perverse, so settled on a fix that changed some of the perverse behaviour while also fixing the "ReDOS" issue (Snyk reported it via email as such).
(As with many "ReDOS" "vulns", I have conflicting & complicated thoughts on whether it's reasonable to consider this a security vulnerability in the first place, as Snyk do. That question of labeling doesn't …
=> Improve time complexity of tokenization regex used in diffSentences

src/diff/word.js, src/util/string.js
Like https://github.com/kpdecker/jsdiff/pull/580.
To demonstrate the performance issue, run the following code either before or after applying this change (remember to build):
```
console.time(); diff.diffWords('a' + ' '.repeat(100000) + 'b', 'a' + ' '.repeat(100000) + 'c'); console.timeEnd()
```
On master (before merging this), this takes 17 seconds on my machine; on this branch, it takes a couple of milliseconds.
=> Purge more quadratic-time regexes

index.html, style.css
Two things were broken:
1. Newlines rendered as massive page breaks instead of newlines, because Firefox creates `<div>` elements within the `contenteditable` to represent newlines and our CSS was making them `height: 100%`.
2. We weren't reading the typed content from the editable divs correctly, because you can't just use `textContent` or `innerText` for that - see e.g. https://stackoverflow.com/q/64105609/1709587 and https://stephenhaney.com/2020/get-contenteditable-plaintext-with-correct-linebreaks/
Point 1 is easy to fix, though I worry slightly that some browsers might do really eccentric things (and I don't have a Mac to test Safari). Point 2, there are fixes available (see Stephen Haney's post, or https://stackoverflow.com/a/15349136/1709587) but they're kinda hacky and make me …
=> Fix the gh-pages demo for Firefox

release-notes.md
(I forgot to add these previously.)
=> Add release notes for #581

package.json, yarn.lock
Looks like this was added to support jsdiff's bower release process, which has long since been ripped out.
=> Remove seemingly-unnecessary `semver` dependency

.gitignore
Reasons this is no longer needed:
- all the instructions for contributing this repo say to use yarn, which has never generated npm-debug.log
- since npm 4.2.0, released in 2017, npm *also* doesn't generate npm-debug.log
I noticed this while cross-checking .gitignore against .npmignore to make sure there weren't any weird generated files, not meant to be published, that we were Git-ignoring but forgetting to put in .npmignore. This was the only such inconsistency. We could resolve it by adding the same line to .npmignore, but since npm-debug.log will probably never get generated on anyone's machine ever again while they're working on jsdiff, it's probably better to just remove all reference to it.
=> Remove no-longer-needed npm-debug.log entry from .gitignore

test/patch/create.js
The tests previously didn't cover this scenario. Worth having a test to explicitly document the intended behaviour.
=> Add test for case where oldHeader and newHeader are omitted in structuredPatch call

.npmignore
This is just needed for running mocha tests; there's no reason to publish it.
=> Stop publishing runtime.js to npm

release-notes.md, src/diff/base.js, test/diff/character.js
Another thing uncovered by rewriting in TypeScript with strict mode.
=> Fix async mode return value quirk

test/diff/word.js
Somehow I screwed up https://github.com/kpdecker/jsdiff/pull/613 and merged it with the tests failing and with the sentence I was actually using in the test inconsistent with the one I claimed to be using in the comment above. Also, even if I'd got it right, I wouldn't've actually avoided hitting the inconsistency in Intl.Segmenter's tokenization rules that that PR was specifically trying to avoid, because it considers 他有 (he has) to be one word; I should've used 她有 (she has) which the segmenter sees as two words. This fixes both mistakes.
=> Fix broken diffWords test

src/index.ts, src/types.ts
Adds `ArrayChange` to the type exports. This was originally exported as part of the `@types/diff` package ([code](https://www.npmjs.com/package/@types/diff/v/7.0.2?activeTab=code)), but isn't exported here. Including it will make the v8 type update simpler.
Alternatively, we could cut the type altogether since it hasn't been exported since the v8 release.
=> fix: export ArrayChange type

release-notes.md, src/diff/word.ts, test/diff/word.js
Fixes https://github.com/kpdecker/jsdiff/issues/630
Thanks @SonOfLilit for reporting this!
=> Fix diffWords crashing when used with an Intl.Segmenter on a text with consecutive newlines

package.json
When I run any yarn commands in the jsdiff repo on my current dev machine (which has an installation of Node 24 that shipped with Corepack), Corepack automatically asks to install Yarn 1 and automatically adds a `packageManager` key to `package.json`. I vaguely recall that certain scripts in this repo do (or at least once did) specifically need Yarn 1 so this is probably appropriate. Might as well commit the automatic change.
=> Let Corepack add a packageManager property to package.json
